project:
  name: "MiQ_AdTech_CTR"
  version: "7.5.0"

data:
  raw_path: "data/raw/raw_impressions.parquet"
  processed_path: "data/processed/features.parquet"

model:
  target: "is_clicked"
  test_size: 0.2
  random_state: 42
  params:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    objective: "binary:logistic"

mlflow:
  experiment_name: "MiQ_Ad_CTR_Prediction"
  tracking_uri: "sqlite:///mlflow.db"