name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Java 11 (Required for PySpark)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e . 

    - name: Build Production Artifacts
      run: |
        # In CI, we must generate the model from scratch to ensure path consistency
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m src.data.generate_data
        python -m src.features.build_features
        python -m src.models.train

    - name: Run Unit Tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m pytest tests/ -v -W ignore::DeprecationWarning